# Generated by Django 3.0.3 on 2020-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='imageUrl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='videoUrl',
            field=models.TextField(null=True),
        ),
    ]
