# Generated by Django 3.0.3 on 2020-10-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_auto_20201002_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='imageUrl',
            new_name='imageUrl1',
        ),
        migrations.AddField(
            model_name='word',
            name='imageUrl2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='imageUrl3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='imageUrl4',
            field=models.TextField(null=True),
        ),
    ]
