# Generated by Django 3.0.3 on 2020-10-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_auto_20201003_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
